spring:
  application:
    name: junit-learning
  profiles:
    active: "local"

  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/junit-learning?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456



  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: "classpath:db/migration/mysql"
    schemas: junit-learning
    out-of-order: false

mybatis-plus:
  mapper-locations: "cn/point/cat/middleware/dao/**/**.xml"
  configuration:
    use-actual-param-name: true
    log-impl: 'org.apache.ibatis.logging.stdout.StdOutImpl'
  global-config:
    db-config:
      db-type: MYSQL


